---
abstract: 'A system for implementing database migrations'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  File::Find: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Database-Migrator
requires:
  DBI: 0
  Eval::Closure: 0
  File::Slurp: 0
  File::Temp: 0
  Log::Dispatch: 0
  Log::Dispatch::TestDiag: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Getopt::Dashes: 0
  MooseX::Types: 0
  MooseX::Types::Combine: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Path::Class: 0
  Path::Class: 0
  Test::Fatal: 0
  Test::More: 0.88
  namespace::autoclean: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Database-Migrator
  homepage: http://metacpan.org/release/Database-Migrator
  repository: git://git.urth.org/Database-Migrator.git
version: 0.08
x_authority: cpan:DROLSKY
